### ISSUE TITLE
Twig Profiler

### ISSUE THREAD

**Issue by barryvdh** [maximebf/php-debugbar#192]
There is a WIP PR for Twig to add a Profiler extension: https://github.com/twigphp/Twig/pull/1597

The linked PR for Symfony Webtoolbar shows how this could be implemented. Probably use that instead of the current TwigCollector when it's available. We could also use the TimeData collector to build the call graph.

Keeping this open as a reference, untill the PR is merged. Then we could do an initial PR.

**Comment by Anahkiasen** [comment]
That looks pretty nice, would love to see that in

**Comment by barryvdh** [comment]
Okay it's merged, but not yet tagged.

Perhaps it would be a good idea to create a seperate repository for 3rd party collectors with dependancies? Otherwise we can't require certain versions etc.

**Comment by ChrisWesterfield** [comment]
what is the current status on this?

**Comment by barryvdh** [comment]
Low on my priority list, but open for PRs

**Comment by B0bbyD0llar** [comment]
I have tested this profiler and it is a very good extension. Can anyone implement this? Unfortunately, my skills are not enough for it.
