### ISSUE TITLE
problem with PDO and SQLserveur

### ISSUE THREAD

**Issue by kardagan** [maximebf/php-debugbar#193]
in file TraceablePDOStatement.php line 62/63 you do
            $error = $this->errorInfo();
            $ex = new PDOException($error[2], $error[0]);

but in pdo doc ( http://php.net/manual/en/pdo.errorinfo.php )
0	SQLSTATE error code (a five characters alphanumeric identifier defined in the ANSI SQL standard).

and when it's really an alphanumeric i have this error : 

array (
'type' => 1,
'message' => 'Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])',
'file' => '/RDC/web/STO/eros/application/src/vendor/maximebf/debugbar/src/DebugBar/DataCollector/PDO/TraceablePDOStatement.php',
'line' => 63,
)

because the exception is wating a long not a varchar

**Comment by barryvdh** [comment]
Submitted a fix.
