### ISSUE TITLE
Make search case-insensitive

### ISSUE THREAD

**Issue by tonglil** [maximebf/php-debugbar#194]
If someone could point me in the direction as to where in the js to look for the search bar input I would like to create a PR to do case insensitive searching (for example in the files collector tab).

It would be of great use not to have to remember what casing the filename is in.

**Comment by maximebf** [comment]
You would need to add a flag to fnmatch here: https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/Storage/FileStorage.php#L101
(see: http://devdocs.io/php/function.fnmatch)

**Comment by tonglil** [comment]
@maximebf sorry for the late response, just got the chance to work on this now.

I think we may be confused? I mean the search after the page has loaded.

I believe the code you pointed me to is for when the debugbar is searching through the filesystem to look for files.

**Comment by tonglil** [comment]
Actually I got it :)
