### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by jamesxv7** [maximebf/php-debugbar#197]
I'm trying to setup the php-debugbar but I'm unable to properly configure resources files (mostly css & js files) located in __maximebf/debugbar/src/DebugBar/Resources/*__. I configure the composer autoload secction with the following parameters: 
```
"autoload": {
        "psr-4": {
            "DebugBar\\StandardDebugBar\\": "vendor/maximebf/debugbar/src/"
        }
```
Updated composer autoload and still can't see the debugbar in my project. Any help from the community will be very appreciate.

![phpdebugbar](https://cloud.githubusercontent.com/assets/121668/6142412/728e7736-b18c-11e4-83bc-f4706340dab5.png)

**Comment by barryvdh** [comment]
You don't need to set up the autoloading in Composer, just require the package.

And you need copy the assets to a file in your public webroot, and set that location with setBaseUrl in the JavascriptRenderer.

See http://phpdebugbar.com/docs/rendering.html#assets

**Comment by jamesxv7** [comment]
Thanks a lot @barryvdh for providing light to solve my problem. The demo app was pretty clear:
https://github.com/maximebf/php-debugbar/blob/master/demo/bootstrap.php#L11-L13
