### ISSUE TITLE
Plates collector

### ISSUE THREAD

**Issue by jenolan** [maximebf/php-debugbar#201]
Do you think that it would be possible for you to create a collector for the Plates templating system http://platesphp.com/
It would be greatly appreciated ;-)

Thanks

**Comment by barryvdh** [comment]
I've taken a quick look, but I'm not sure what the best way is.
I guess it would be possible to extend the Engine, override the render() method and add some timing there , similar to the TraceableTwigEnvironment. Something like this perhaps?

    <?php

    use League\Plates\Engine;
    use DebugBar\DataCollector\TimeDataCollector;

    class TraceableEngine extends Engine 
    { 
        protected $twig;
        protected $timeDataCollector;

        public function __construct(Engine $engine, TimeDataCollector $timeDataCollector = null)
        {
            $this->engine = $engine;
            $this->timeDataCollector = $timeDataCollector;
        }

        public function render($name, array $data = array())
        {
            $start = microtime(true);
            $result = parent::render($name, $data);
            $end = microtime(true);
            
            if ($this->timeDataCollector) {
                $name = sprintf("plates.render(%s)", $name);
                $this->timeDataCollector->addMeasure($name, $start, $end, $data, 'Plates');
            }
            return $result;
        }
    }

ping @reinink for better ideas ;)

**Comment by barryvdh** [comment]
And to clarify, you would wrap the original engine in the new TraceableEngine

    // Create the Collector
    $timeDataCollector = new DebugBar\DataCollector\TimeDataCollector();
    $debugbar->addCollector($timeDataCollector);

    // Or get an existing one
    $timeDataCollector = $debugbar['time'];

    // Create new Plates instance
    $templates = new League\Plates\Engine('/path/to/templates');

    // Wrap the Engine in the TraceableEngine
    $templates = new TraceableEngineEngine($templates, $timeDataCollector);

    // Render a template
    echo $templates->render('profile', ['name' => 'Jonathan']);

But I haven't tested any of this, but let me know the results!

**Comment by jenolan** [comment]
So both messages combined .. give that a go?

**Comment by reinink** [comment]
Forgive my ignorance gents, but what do you mean by collector?

**Comment by barryvdh** [comment]
A collector in the case of php debugbar is a class that collects some information. For example for templates, to get information about which templates are rendered, whit what variables, how long it took etc.

**Comment by reinink** [comment]
Ahh, sorry, I got confused and thought this was an actual Plates issue. Makes sense in the context of php-debugbar. :)
