### ISSUE TITLE
Missing fontawesome file

### ISSUE THREAD

**Issue by bobd91** [maximebf/php-debugbar#207]
I am getting the following 404 Not Found in my console

http://........vendor/font-awesome/fonts/fontawesome-webfont.woff2?v=4.3.0 

This file exists in the 4.3.0 fontawesome release but not the php-debugbar repo

**Comment by jeff1985** [comment]
Same problem here!

**Comment by barryvdh** [comment]
Should be fixed in `v1.10.5`
