### ISSUE TITLE
Twig coillector and Slim

### ISSUE THREAD

**Issue by borgogelli** [maximebf/php-debugbar#208]
Hi

I'm using Slimframework with Twig view and DebugBar

<pre>
$debugbar = new StandardDebugBar();
// Twig collector
$twig = $app->view->getEnvironment(); // $app is an instance of the class Slim\Slim
$env = new TraceableTwigEnvironment($twig);
$debugbar->addCollector(new TwigCollector($env));
</pre>

when i load a web page, on the debugbar I always read
<pre>
0 templates were rendered
</pre>

Any advice ?

Thank you in advance

**Comment by barryvdh** [comment]
Can you replace the view environment? eg. `$app->view->setEnvironment($env);`?

But we'll probably rework the Twig collector soon.

**Comment by borgogelli** [comment]
you're right, but I don't know how to replace/set the TraceableTwigEnvironment in Slim

**Comment by borgogelli** [comment]
you're right, but I don't know how to replace/set the TraceableTwigEnvironment in Slim view
So I close that issue and open a new one in the right project
https://github.com/slimphp/Slim-Views/issues/45
Thank you.
