### ISSUE TITLE
AJAX Loading causes view to jump

### ISSUE THREAD

**Issue by pachonk** [maximebf/php-debugbar#250]
If I'm trying to look at a particular request, and another ajax request come in... The view changes to the most recent ajax request.

**Comment by dubpub** [comment]
Any progress?

**Comment by james-johnston-thumbtack** [comment]
I added an option to disable that behavior: https://github.com/maximebf/php-debugbar/pull/315

So I would consider this issue closed?

**Comment by pachonk** [comment]
Sorry, I'm not nearly as active in PHP community so I haven't tried/tested this.
It looks like that would do the trick, though!

**Comment by barryvdh** [comment]
Probably need an option here though

**Comment by barryvdh** [comment]
Oh sorry, this is php-debugbar, not laravel-debugbar. Closing this as fixed :)
