### ISSUE TITLE
Ability to use custom SQLLogger

### ISSUE THREAD

**Issue by eng1neer** [maximebf/php-debugbar#255]
The DoctrineCollector's implementation seems to be unnecessary coupled to concrete DebugStack and it's better to use SQLLogger interface here:

https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/Bridge/DoctrineCollector.php#L42

It will allow to use custom SQLLogger implementations.

**Comment by barryvdh** [comment]
Can you create a PR?

**Comment by eng1neer** [comment]
Here it is:
https://github.com/maximebf/php-debugbar/pull/256

**Comment by eng1neer** [comment]
Closing along with #256
