### ISSUE TITLE
Missing `original padding in calculation` in latest release

### ISSUE THREAD

**Issue by sanex3339** [maximebf/php-debugbar#258]
Hi, i look at latest commit for 
https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/Resources/debugbar.js
and found here very nice changes for padding-bottom calculation.

But these changes were not included in the release, the same day.

Can you release new version with this changes, because 26px padding-bottom breaks our layout.

**Comment by barryvdh** [comment]
tagged 1.11.1

**Comment by sanex3339** [comment]
thankyou
