### ISSUE TITLE
Error using Swift Mail collector on Exception

### ISSUE THREAD

**Issue by hackel** [maximebf/php-debugbar#265]
I'm getting the following ErrorException in SwiftLogCollector.php line 37:
`Undefined property: DebugBar\Bridge\SwiftMailer\SwiftLogCollector::$_log

I don't see a reference to $_log anywhere else in the code.

Note that I'm using barryvdh/laravel-debugbar, but I believe this problem is realted to php-debugbar.  I'm running version 1.11.1 with Swift Mailer 5.4.1.

**Comment by tomsarduy** [comment]
I'm getting the same error, when I try to send an email

**Comment by barryvdh** [comment]
I think it should return the messages instead

```
public function dump()
{
	$dump = '';
	foreach ($this->messages as $message) {
		if ($messages['is_string']) {
			$dump .= $message['message'] . PHP_EOL;
		}
	}

	return $dump;
}
```

**Comment by flo-sch** [comment]
+1, having the same issue here.

It happends when SwiftMailer triggers an exception (such as Swift_TransportException), for instance when the mailer is misconfigured (local environment).

**Comment by msonowal** [comment]
still exists

**Comment by ana-lisboa** [comment]
Still exists..

my die and dump of $this, inside the dump() function

![image](https://user-images.githubusercontent.com/12087482/49094733-cfaeff00-f25e-11e8-9577-4e2802264722.png)

**Comment by MCMainiac** [comment]
@maximebf Why does this still exist? It's 2019!
