### ISSUE TITLE
[PHP 7.1] A non well formed numeric value encountered

### ISSUE THREAD

**Issue by laravelish** [maximebf/php-debugbar#284]
Hello, after upgrading from php 5.6 to 7.1 i am getting this error in laravel 5.2 using https://github.com/barryvdh/laravel-debugbar
`Debugbar exception: A non well formed numeric value encountered`

and the debugbar does not display anymore

**Comment by trtstm** [comment]
I have the same issue with Ubuntu 14.04.4 LTS and PHP 7.1.

**Comment by barryvdh** [comment]
Do you have a stack trace,  where is it coming from?

**Comment by trtstm** [comment]
Nope just the same message as laravelish. I don't have this error on php 7.0.8.

**Comment by barryvdh** [comment]
Weird. Most issues I can find on the internet are related to date/strtotime parsing, but not sure why that would affect the debugbar.

**Comment by michaeljhopkins** [comment]
I'm seeing the same issue. I too am not given a stack trace and don't know the line

**Comment by thanosalexander** [comment]
Maybe this helps
https://github.com/symfony/symfony/commit/d422939f6c3ae33435b0208ff363fac9d97ebf6b

**Comment by barryvdh** [comment]
Do you have a matching pr for more info?

**Comment by barryvdh** [comment]
Okay so https://github.com/symfony/symfony/issues/19377
It's tagged today, so hopefully that will fix it. Can you run composer update to verify this doesn't happen anymore?

**Comment by trtstm** [comment]
Yup that fixed it for me.
