### ISSUE TITLE
 Wrong replacement params text pdo  with same part text

### ISSUE THREAD

**Issue by webmailcontatos** [maximebf/php-debugbar#350]
```
$sql = 'select *
from geral.exame_part ep
where ep.id_exame = :id_exame and 
      ep.id_exame_situacao = :id_exame_situacao';
$params  = [
     'id_exame'=>1,
     'id_exame_situacao'=>1
];
```

Expected log :
select * from geral.exame_part ep where ep.id_exame = '1' and ep.id_exame_situacao = '1'
Current log :
select * from geral.exame_part ep where ep.id_exame = '1' and ep.id_exame_situacao = '1'_situacao

**Comment by barryvdh** [comment]
Fixed with #351
