### ISSUE TITLE
Websites own jQuery gets replaced with the debug bars jQuery version

### ISSUE THREAD

**Issue by forceedge01** [maximebf/php-debugbar#356]
Hi,

It seems the debug bar is replacing the sites jQuery javascript library with its own version which is quite dated. We have got 3.1.1 on our site, but when the debug bar is enabled it comes up as 1.11.2.

Steps to replicate:
The simplest way i've found to check is to enable/disable the debug bar and check what happens.
1. Enable debug bar and load the page.
2. To get the version of jquery run `alert( $().jquery );` in console.
3. Disable the debug bar and reload the page.
4. To get the version of jquery run `alert( $().jquery );` in console.

Can we make this behaviour optional? Also it may seem that this should not affect the page since the debug bar loads at the very end, but loading is mostly async. A callback waiting for anything to happen could be calling on the debug bars jQuery rather than the site's own jQuery library.

How did this issue manifest itself: We suspect we've got an issue relating to this, but are not 100% sure just yet. But it has raised a few eyebrows as to whether our test environment is even reliable given its got different versions of jQuery from production.

Thanks,
Wahab Qureshi.

**Comment by aik099** [comment]
There seem to be a protection against that where jQuery is loaded in non-conflict mode that doesn't overwrite global `$` variable: https://github.com/maximebf/php-debugbar/blob/e6f0b5a48d98e00e4ecda7cdd6bd59b1f04ea70a/src/DebugBar/JavascriptRenderer.php#L61

Not sure why it doesn't work.

**Comment by barryvdh** [comment]
You can so disable some vendor assets

**Comment by barryvdh** [comment]
See http://phpdebugbar.com/docs/rendering.html#managing-jquery-conflicts

**Comment by forceedge01** [comment]
Thanks very much for your help, this gives me all I need.
