### ISSUE TITLE
【help】How can I integrate this package in yaf framework ?

### ISSUE THREAD

**Issue by OneCodeMonkey** [maximebf/php-debugbar#415]
How can I integrate this package in yaf framework ?
#### [yaf](https://github.com/laruence/yaf)

**Comment by igorsantos07** [comment]
you mean use it with yaf in your own project, or you're a yaf developer and want to put it inside the framework / make a package?

**Comment by OneCodeMonkey** [comment]
> you mean use it with yaf in your own project, or you're a yaf developer and want to put it inside the framework / make a package?

yes, I am using yaf framework. There is no suitable packages to debug within it. Debug is not much convenient.

**Comment by OneCodeMonkey** [comment]
> you mean use it with yaf in your own project, or you're a yaf developer and want to put it inside the framework / make a package?

Or maybe symfony/debug will be a choice. I'm not sure :)

**Comment by barryvdh** [comment]
You should be able to find alle documentation about rendering and creating collectors: http://phpdebugbar.com/docs/
