### ISSUE TITLE
Update twig usings

### ISSUE THREAD

**Issue by Stijn98s** [maximebf/php-debugbar#423]
current twig usings are deprecated since 2.7. for example `Twig_Environment` is now `Twig\Environment`

**Comment by leomoty** [comment]
I got curious how much work would be necessary to make this work, as it turns out, not much. I'll try to clean up a bit and make a PR.

![image](https://user-images.githubusercontent.com/1463740/66402602-79046c80-e9bb-11e9-86d2-7c9385aa6bac.png)

**Comment by leomoty** [comment]
Also it seems that `DebugBar\Bridge\TwigProfileCollector` works out of box, it just doesn't contribute to the timeline:

![image](https://user-images.githubusercontent.com/1463740/66403685-612de800-e9bd-11e9-97ed-e48f096f2c96.png)

It is described here:

https://github.com/maximebf/php-debugbar/blob/master/docs/bridge_collectors.md#twig-profiler

**Comment by leomoty** [comment]
Hey @barryvdh, I went a bit further, the current demo only works for `twig/twig <2`, and it still has two warnings:

```

Warning: Declaration of DebugBar\Bridge\Twig\TraceableTwigTemplate::hasBlock($name) should be compatible with Twig\Template::hasBlock($name, ?array $context = NULL, array $blocks = Array) in /var/www/html/src/DebugBar/Bridge/Twig/TraceableTwigTemplate.php on line 19

Warning: Declaration of DebugBar\Bridge\Twig\TraceableTwigTemplate::getBlockNames() should be compatible with Twig\Template::getBlockNames(?array $context = NULL, array $blocks = Array) in /var/www/html/src/DebugBar/Bridge/Twig/TraceableTwigTemplate.php on line 19
```
Would you accept a PR changing the current demo to use `DebugBar\Bridge\TwigProfileCollector` instead? Maybe even drop the TraceableTwig*, since it doesn't seem to add anything of value and has been broken for v2?

**Comment by barryvdh** [comment]
Ehh, yeah I'm not totally familiar with the Demo setup. I don't think its rebuilt automatically.

But we can deprecate the v1 stuff.

**Comment by leomoty** [comment]
The twig demo itself has `twig/twig` as *, so it will always pick latest.

**Comment by Stijn98s** [comment]
still not fixed. now twig 3.0 is released all PSR-0 classes are removed and debugbar is broken with twig
