### ISSUE TITLE
Add v1.15.1 to Packagist

### ISSUE THREAD

**Issue by devnix** [maximebf/php-debugbar#424]
Hey! I would love to update my php-debugbar installation, but it seems like the `v1.15.1` version is not tagged at Packagist, so I would be forced to set my `minimum-stability` to `dev`

**Comment by caugner** [comment]
`v1.15.1` is available since  2019-09-24, but `v.1.16.0` isn't. 

However, @maximebf has already been pinged [here](https://github.com/maximebf/php-debugbar/pull/422#issuecomment-536828549).

**Comment by caugner** [comment]
@devnix The latest version `v.1.16.0` is now available.

**Comment by devnix** [comment]
Thank you!
