### ISSUE TITLE
Syntax error with php5.6

### ISSUE THREAD

**Issue by fralbo** [maximebf/php-debugbar#426]
Hello,

I'm trying to use your plugin with the Fat-Free framework and everything is ok running php 7.3;
Now my problem is that I have an application to develop on machines providing php 5.6.
I tested on 3 environments, my target (ubuntu 14.04) a ubuntu 16.04 and wamp64, on all env running php5.6 I get the same result:

Internal Server Error

Fatal error: syntax error, unexpected '('

[vendor/symfony/var-dumper/Cloner/AbstractCloner.php:246]

Is there any chance to fix this issue?

Kind regards,
Alain

**Comment by barryvdh** [comment]
I think you installed a version that is to new from var-dumper. But if you configure your composer.json correctly, it should install only compatible versions (by setting the platform config)
