### ISSUE TITLE
Feature Request: show slowest queries

### ISSUE THREAD

**Issue by regularlabs** [maximebf/php-debugbar#454]
It would be useful to be able to order the queries by time they took. Or have filter, like: show all queries that took longer than 100 ms.

**Comment by formikaio** [comment]
It could be quickly done using JavaScript. What do you think about something like [this](https://github.com/barryvdh/laravel-debugbar/issues/656#issuecomment-525291678)?

**Comment by regularlabs** [comment]
Yeah, but would have to be solved in core. And I am not getting involved. If it doesn't get sorted in core, I'll work my way around it (like always).

**Comment by regularlabs** [comment]
Because of lack of interest and activity, closing this.
