### ISSUE TITLE
setDumpHeader error after upgrading symfony/var-dumper to v5.3.4

### ISSUE THREAD

**Issue by joostvanhoof** [maximebf/php-debugbar#474]
After symfony/var-dumper was upgraded from v5.3.3 to v5.3.4 I'm getting:

**Symfony\Component\VarDumper\Dumper\HtmlDumper::setDumpHeader(): Argument #1 ($header) must be of type string, null given, called in /Users/user/Documents/dev/project/vendor/maximebf/debugbar/src/DebugBar/DataFormatter/DebugBarVarDumper.php on line 288**

Line 288 is `$dumper->setDumpHeader(null);`

Not sure what is going on here but I'm guessing this is a bug?

**Comment by modernben** [comment]
Getting this as well

**Comment by danteese** [comment]
Same

**Comment by ltsochev-dev** [comment]
Not sure who has to fix it. Basically symfony/var-dumper have added a string requirement in the setDumpHeader() method and they haven't gotten around working with NULL. I think this is a var dumper bug.

**Comment by antonioribeiro** [comment]
Yeah, Symfony just broke the Internet 😆

I just [reported it](https://github.com/symfony/symfony/issues/42272).

**Comment by antonioribeiro** [comment]
If you want to just "move on" for now: add to your `composer.json` file: `"symfony/var-dumper":"<5.3.4"`, to force a downgrade:

<img width="653" alt="Screenshot 2021-07-26 at 23 37 13" src="https://user-images.githubusercontent.com/3182864/127062569-e4307a1f-0ae1-455d-8400-5e50695e8791.png">

**Comment by rrpadilla** [comment]
Submitted a [PR](https://github.com/symfony/symfony/pull/42273) to the Symfony repo to fix this issue.

**Comment by nicolas-grekas** [comment]
I'm seeing this line in the code:

> $dumper->setDumpHeader(null); // this will cause the default dump header to regen

Maybe extracting the assets can happen in the constructor so that calling setDumpHeader is not required? This will allow you to releas an immediate fix for the issue.

**Comment by mr-pack** [comment]
Changed `$dumper->setDumpHeader(null)`
to `$dumper->setDumpHeader('');`
and it works

**Comment by barryvdh** [comment]
Sorry about this, I'll take a look. I don't see an immediate way to reset the header, so will see what the best course of action is. Setting it to `''` will probably remove all styling/scripts, so might not be preferred.

**Comment by barryvdh** [comment]
I created a PR here: https://github.com/maximebf/php-debugbar/pull/475
This doesn't change the logic, just adds a separate method to set the header to null, to preserve existing behavior.

**Comment by rrpadilla** [comment]
@barryvdh could you enable the [Packagist](https://packagist.org/packages/maximebf/debugbar) service hook? **This package is not auto-updated.**
Existing packages without auto-updating (GitHub/BitBucket hook) will be crawled once a week for updates. You can see it [here](https://packagist.org/about#how-to-update-packages).
Thanks.

**Comment by barryvdh** [comment]
v1.17 is live now. I forced the refreshed. Unfortunately I can't add the webhooks myself :(
