### ISSUE TITLE
addMessage throws error when the $message is not string 

### ISSUE THREAD

**Issue by armanist** [maximebf/php-debugbar#476]
After updating the package from 1.15 to 1.17 getting error when the $message is not a string

**strtr() expects parameter 1 to be string, array given**

vendor\maximebf\debugbar\src\DebugBar\DataCollector\MessagesCollector.php

Lines: 208-209
```
        // interpolate replacement values into the message and return
        return strtr($message, $replace);
```

**Comment by barryvdh** [comment]
How are you using adding the message?

**Comment by barryvdh** [comment]
I think you are using the PSR-3 methods? That follows https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#12-message

Can you check https://github.com/maximebf/php-debugbar/pull/477 ? /cc @Rudloff
