### ISSUE TITLE
TwigProfileCollector not compatible with Twig 3/namespaces

### ISSUE THREAD

**Issue by xvilo** [maximebf/php-debugbar#478]
It seems that the `TwigProfileCollector` is not compatible with Twig 3 and the namespace structure introduced in Twig 2. I have a working variant for Twig Namspaces locally and would like to upstream these. 

However, I would like to start a small discussion about it's backwards compatibility:
1. I can update the class as is, this would remove compatibility with Twig 1
2. We could create a `NamespacedTwigProfileCollector` variant and modernize it a bit more

**Comment by barryvdh** [comment]
Should be fixed now right?
