### ISSUE TITLE
PHP 8.1 deprecation notices

### ISSUE THREAD

**Issue by rowhel95** [maximebf/php-debugbar#488]
- DebugBar\DataCollector\AggregatedCollector needs #[ReturnTypeWillChange]
- strtolower(): Passing null to parameter 1 ($string) of type string is deprecated | /vendor/maximebf/debugbar/src/DebugBar/JavascriptRenderer.php | 808
- preg_match(): Passing null to parameter 2 ($subject) of type string is deprecated | /vendor/maximebf/debugbar/src/DebugBar/JavascriptRenderer.php | 792
- substr(): Passing null to parameter 1 ($string) of type string is deprecated | /vendor/maximebf/debugbar/src/DebugBar/JavascriptRenderer.php | 792

**Comment by xvilo** [comment]
I've created this PR as a quick fix: https://github.com/maximebf/php-debugbar/pull/489 could be fixed differently, but this does the job.

**Comment by rowhel95** [comment]
Still needs  #[\ReturnTypeWillChange] for DebugBar\DataCollector\AggregatedCollector

**Comment by barryvdh** [comment]
Can you PR that?
