### ISSUE TITLE
Latest Accepted PR not Reflected on Packagist

### ISSUE THREAD

**Issue by arminlinzbauer** [maximebf/php-debugbar#493]
I just tried to composer-install from packagist instead of my custom composer.json repository configuration after my PR was accepted yesterday, but the change isn't available on packagist `dev-master` yet. When can I expect a refresh on packagist?

**Comment by arminlinzbauer** [comment]
Related to #492

**Comment by barryvdh** [comment]
Should be reflected on dev-master now.

**Comment by arminlinzbauer** [comment]
Thank you 👍
