### ISSUE TITLE
Package is not auto-updated on packagist

### ISSUE THREAD

**Issue by hmazter** [maximebf/php-debugbar#499]
Is there any reason why this package is not auto-updates on packagist?

Sorry to bother you if this has been talked about before or there is a valid reason to not auto-update.

Here is the instruction to set up auto-update https://packagist.org/about#how-to-update-packages

https://packagist.org/packages/maximebf/debugbar
![Screenshot 2022-02-10 at 19 43 15](https://user-images.githubusercontent.com/805377/153475177-ed08438b-9c9d-4c7c-90f7-2af81c01583a.png)

**Comment by barryvdh** [comment]
I've updated manually. I'm not a maintainer so cannot add the push hook.
