### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by Yannik** [maximebf/php-debugbar#562]
Hi @barryvdh,

would it be possible for you to tag a new release?

I really need some of the latest commits, especially https://github.com/maximebf/php-debugbar/commit/847216e60544258c881f2733d699bbcfeefac0fc (since it fixes the csp issues caused by jquery not propagating the nonce to its child elements)

Thanks :-)

**Comment by Yannik** [comment]
@parallels999 How comes? The last release was on feb 4th, so it's about time, is it not?

**Comment by parallels999** [comment]
>is it not? 

Yes, But it's a matter of free time, that's the hard part.

**Comment by parallels999** [comment]
Maybe it will be our lucky day and there will be a release 😄😄

**Comment by barryvdh** [comment]
Yeah I'll try to test it later. Am I missing any important PR now? The memory stuff I'm not really comfortable with without testing.

**Comment by Yannik** [comment]
@barryvdh I will add one more PR to fix the dynamically generated inline styes in `widgets.js` ([here](https://github.com/maximebf/php-debugbar/blob/fdc4eec1f54adbc65934cab0bbb996f4b7359b6c/src/DebugBar/Resources/widgets.js#L502) and [here](https://github.com/maximebf/php-debugbar/blob/fdc4eec1f54adbc65934cab0bbb996f4b7359b6c/src/DebugBar/Resources/widgets.js#L508)). Currently working on it. Would be great to get it into the release.

**Comment by Yannik** [comment]
@barryvdh Done: #564 

No more `style-src` csp errors! :tada:

**Comment by barryvdh** [comment]
https://github.com/maximebf/php-debugbar/releases/tag/v1.19.0
