### ISSUE TITLE
Show PHP warnings/errors/notices in "Messages"

### ISSUE THREAD

**Issue by elshobokshy** [maximebf/php-debugbar#583]
Hello,
I've turned off the display_errors in my php.ini, cuz I'd like to show all errors/warnings/notices in the debugbar. I've no idea how to proceed tho, is there a way to do that automatically using the debugbar?
Thanks :)

**Comment by parallels999** [comment]
Use a exception handler

**Comment by elshobokshy** [comment]
And [maybe I will](https://stackoverflow.com/questions/15036831/php-get-warning-and-error-messages), thank you for the idea!!!
