### ISSUE TITLE
InternalError: too much recursion for v1.21+

### ISSUE THREAD

**Issue by czernika** [maximebf/php-debugbar#614]
I'm using Laravel with [Orchid](https://github.com/orchidsoftware/platform) admin panel and [Laravel debugbar](https://github.com/barryvdh/laravel-debugbar)

Since last update I've noticed that debugbar dissapears when I navigate to some page - it works on initial load however. At first I thought it something with project code/deps, but digging deeper I found out it was this particular package (which is laravel-debugbar dependency) and more specifically version 1.21+ (I've installed version 1.20.1 and debugbar start working again)

Orchid is using [Hotwire](https://hotwired.dev/) under the hood so I believe it has to be something with it

![Снимок экрана от 2024-03-11 18-45-03](https://github.com/maximebf/php-debugbar/assets/86893348/6356c97f-59b1-4e19-b84f-b4e38d078ab8)

**Comment by erikn69** [comment]
Hi, please try https://github.com/maximebf/php-debugbar/pull/613#issuecomment-1988590018
`CTRL + SHIFT + R` for reload js cache

**Comment by czernika** [comment]
@erikn69 Ah yes thanks. Problem was specific for 1.21.0 (I didn't noticed 1.21.1 release about hour ago as start debugging earlier - with 1.21.1 everything back to normal)

**Comment by erikn69** [comment]
1.21.1 was a regression,
I was referring to the fix that I proposed on https://github.com/maximebf/php-debugbar/pull/613#issuecomment-1988590018

**Comment by erikn69** [comment]
I added  #615, 
If you could confirm that it works correctly for you it would be very helpful, 
so if it does merge you won't have the same problem again.

**Comment by czernika** [comment]
@erikn69 on 1.21.0 with proposed changes from #615 it works

**Comment by erikn69** [comment]
thank you very much ❤️
