### ISSUE TITLE
DoctrineCollector: foreach loop in getParameters fails on "null" values.

### ISSUE THREAD

**Issue by ch-feedbackpeople** [maximebf/php-debugbar#662]
Hello,

I came across an error in the DoctrineCollector. For some reason, the value of $query['params'] can be "null". The query who triggered this in my case was a "START TRANSACTION" with no others parameters. Because of that the foreach loop in that function fails with a "foreach() argument must be of type array|object, null given" error.

**Comment by parallels999** [comment]
Feel free to make a PR with the fix

**Comment by erikn69** [comment]
Try #663

**Comment by ch-feedbackpeople** [comment]
Yeah, that works.
