### ISSUE TITLE
v1.23 error: :array to string converstion 

### ISSUE THREAD

**Issue by mostafasy** [maximebf/php-debugbar#680]
- version v1.22.3 : it works
- last version 1.23 it will throw an e-warning exception in doctrine collector  in row 89: 
-https://github.com/maximebf/php-debugbar/blame/v1.23.0/src/DebugBar/Bridge/DoctrineCollector.php
- the $param can be dimensional array and then impload will be throw this error: array to string converstion ..what the best soultion to fix this

**Comment by erikn69** [comment]
Hi, try #681 and let your review there
